Doit\WebBundle\Entity\Comment:
    type: entity
    table: comment
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
