Doit\WebBundle\Entity\UserStat:
    type: entity
    table: user_stat
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: 用户id
            column: user_id
        followNum:
            type: integer
            nullable: false
            unsigned: false
            comment: '关注数'
            default: '0'
            column: follow_num
        fansNum:
            type: integer
            nullable: false
            unsigned: false
            comment: 粉丝数
            default: '0'
            column: fans_num
    lifecycleCallbacks: {  }
