Doit\WebBundle\Entity\UserProfile:
    type: entity
    table: user_profile
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: 用户id
            column: user_id
        realName:
            type: string
            nullable: false
            length: 20
            fixed: true
            comment: 真实姓名
            default: ''
            column: real_name
        avatarSmall:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 头像小图路径
            default: ''
            column: avatar_small
        avatarMiddle:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 头像中图路径
            default: ''
            column: avatar_middle
        avatarBig:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 头像大图(原图)路径
            default: ''
            column: avatar_big
        phone:
            type: integer
            nullable: false
            unsigned: false
            comment: 手机号
            default: '0'
        birthday:
            type: string
            nullable: false
            length: 10
            fixed: true
            comment: 生日
            default: ''
        sex:
            type: boolean
            nullable: false
            comment: '性别 1男，2女，3保密'
            default: '1'
        hometownProvince:
            type: smallint
            nullable: false
            unsigned: false
            comment: 家乡所在省，存储数字
            default: '0'
            column: hometown_province
        hometownCity:
            type: smallint
            nullable: false
            unsigned: false
            comment: 家乡所在城市
            default: '0'
            column: hometown_city
        qq:
            type: bigint
            nullable: false
            unsigned: false
            comment: 'QQ号码'
            default: '0'
        province:
            type: smallint
            nullable: false
            unsigned: false
            comment: 当前所在省
            default: '0'
        city:
            type: smallint
            nullable: false
            unsigned: false
            comment: 当前所在城市
            default: '0'
        blood:
            type: boolean
            nullable: false
            comment: '血型：1O型， 2A型，3B型，4AB型，5稀有血型'
            default: '0'
        marriage:
            type: boolean
            nullable: false
            comment: 婚姻：1单身，2恋爱中，3订婚，4已婚，5离异
            default: '0'
        bodytype:
            type: boolean
            nullable: false
            comment: 体型：1苗条，2匀称，3健壮，4高大，5小巧，6丰满，7高挑，8较胖，9较瘦，10运动型，0保密
            default: '0'
        workStatus:
            type: boolean
            nullable: false
            comment: '工作状态：0其它，1学生，2已工作'
            default: '0'
            column: work_status
    lifecycleCallbacks: {  }
