homepage:
    pattern:  /
    defaults: { _controller: DoitWebBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#register:
#    pattern:   /register
#    defaults:  { _controller: DoitWebBundle:Register:index }
#
#register_success:
#    pattern:   /register/success
#    defaults:  { _controller: DoitWebBundle:Register:success }
#
#register_email_send:
#    pattern:   /register/email/send/{id}/{hash}
#    defaults:  { _controller: DoitWebBundle:Register:sendEmail }
#
#register_email_verify:
#    pattern:   /register/email/verify
#    defaults:  { _controller: DoitWebBundle:Register:verifyEmail }
#
#register_email_check:
#    pattern:   /register/email/check
#    defaults:  { _controller: DoitWebBundle:Register:checkEmail }
#
#
#register_test_update:
#    pattern:   /register/test/update/{id}
#    defaults:  { _controller: DoitWebBundle:Register:update }
#
#login:
#    pattern:   /login
#    defaults:  { _controller: DoitWebBundle:Login:index }
#
#login_check:
#    pattern:   /login_check
#    defaults:  { _controller: DoitWebBundle:Login:loginCheck }
#
#logout:
#    pattern:   /logout
#    defaults:  { _controller: DoitWebBundle:Login:logout }

adminhome:
    pattern:  /admin
    defaults: { _controller: DoitWebBundle:Default:admin }
