<?php

namespace Acme\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findByCateTname($tname)
	{
		$category = $this->getEntityManager()->getRepository('AcmeBlogBundle:Category')->findOneByTname($tname);
		return $this->createQueryBuilder('a')
			->where('a.category = :category')
			->setParameter('category', $category)
			->orderBy('a.id', 'ASC')
			->getQuery()
			->getResult();
	}
}
