<?php

namespace Acme\BlogBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends DocumentRepository
{
}