acme_blog_homepage:
    pattern:     /
    defaults: { _controller: AcmeBlogBundle:Default:index }

acme_blog_list:
    pattern:     /list
    defaults: { _controller: AcmeBlogBundle:Default:list }


acme_blog_show:
    pattern:     /show/{id}
    defaults: { _controller: AcmeBlogBundle:Default:show}
    requirements:
        id: \d+