<?php

namespace Doit\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserByEmailAndPassword($username, $password)
    {
        return $this->createQueryBuilder('u')
            ->where('u.email = :email or u.username = :username')
            ->andWhere('u.password = :password')
            ->setParameter('email', $username)
            ->setParameter('username', $username)
            ->setParameter('password', $password)
            ->getQuery()
            ->getSingleResult();
    }
}
